name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-dev:
    name: Build & Deploy (dev)
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: frontend
        run: bun install --frozen-lockfile

      - name: Build (dev)
        working-directory: frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_DOCS_URL: https://docs.dev.searchandmerch.com
          VITE_ORGANISATION_ID: ${{ secrets.VITE_ORGANISATION_ID }}
          VITE_FEED_ID : ${{ secrets.VITE_FEED_ID }}
          VITE_RECOMMENDATION_ID : ${{ secrets.VITE_RECOMMENDATION_ID }}
        run: bun run build

      - name: Configure AWS credentials (dev)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 (dev)
        run: |
          aws s3 sync frontend/dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront (dev)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
